# Generated by Django 5.2 on 2025-04-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
