# Generated by Django 5.2 on 2025-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choy', '0002_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='valid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
