# Generated by Django 5.2 on 2025-04-06 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choy', '0003_transaction_amount_transaction_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
